version: '3'
services:
  php:
    build:
      context: . # Récupère le Dockerfile à la racine pour override l'image de base de php
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./session:/var/lib/php/sessions
    extra_hosts:
      - host.docker.internal:host-gateway
    links:
      - mysql

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./session:/var/lib/php/sessions
    links:
      - php

  mysql:
    image: mysql:8
    user: mysql
    volumes:
      - ./docker/data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    command: ['--default-authentication-plugin=mysql_native_password']

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    links:
      - mysql
      - php